server {
    listen 443 ssl http2;
    server_name api.lexilingo.me;

    ssl_certificate /etc/letsencrypt/live/api.lexilingo.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/api.lexilingo.me/privkey.pem;

    client_max_body_size 25m;

    location / {
        proxy_pass http://<PRIVATE_IP_BACKEND>:8000;
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_connect_timeout 15s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }
}

server {
    listen 443 ssl http2;
    server_name ai.lexilingo.me;

    ssl_certificate /etc/letsencrypt/live/ai.lexilingo.me/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ai.lexilingo.me/privkey.pem;

    client_max_body_size 25m;

    location / {
        proxy_pass http://<PRIVATE_IP_AI>:8001;
        include /etc/nginx/snippets/proxy-common.conf;
        proxy_connect_timeout 30s;
        proxy_send_timeout 180s;
        proxy_read_timeout 180s;
    }
}
